name: scottjallen
favicon: null
layout_spectrum: 0.75531
typography_spectrum: 0.7923
title: 'Scott J. Allen, Ph.D'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72417208-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
