name: scottjallen
favicon: null
layout_spectrum: 0.75531
typography_spectrum: 0.7923
title: 'Scott J. Allen, Ph.D'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72417208-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bf8448'
    - '#212121'
    - '#f3f0eb'
    - '#8f501b'
    - '#fdc4b0'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
